_wandb:
    value:
        cli_version: 0.21.3
        e:
            3cpx97t1kfv2s8g0805ixz5t06iv28tz:
                args:
                    - --train_data
                    - data_train.csv:latest
                    - --model_config
                    - /home/aziz9788/pipe-line/starter/random_forest_config.yml
                    - --export_artifact
                    - model_export
                    - --random_seed
                    - "42"
                    - --val_size
                    - "0.3"
                    - --stratify
                    - genre
                codePath: starter/random_forest/run.py
                codePathLocal: run.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "21507162112"
                email: 3ziz9788@gmail.com
                executable: /home/aziz9788/miniconda3/envs/mlflow-a3629828cd971ffe646011f938d3373bb5d5ef95/bin/python
                git:
                    commit: 08bac113ceb53fddf848307bff53a248e7317fe6
                    remote: https://github.com/Abdulaziz-97/pipe-line.git
                gpu: NVIDIA GeForce RTX 2080 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2080 SUPER
                      uuid: GPU-76bcb42e-862b-9f0c-a767-8fcec33ef32e
                host: DESKTOP-H5LB02V
                memory:
                    total: "8296493056"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/aziz9788/pipe-line/starter/random_forest/run.py
                python: CPython 3.13.7
                root: /home/aziz9788/pipe-line/starter/random_forest
                startedAt: "2025-09-24T19:36:04.145324Z"
                writerId: 3cpx97t1kfv2s8g0805ixz5t06iv28tz
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 62
            "4": 3.13.7
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
export_artifact:
    value: model_export
features:
    value:
        categorical:
            - time_signature
            - key
        nlp:
            - text_feature
        numerical:
            - danceability
            - energy
            - loudness
            - speechiness
            - acousticness
            - instrumentalness
            - liveness
            - valence
            - tempo
            - duration_ms
random_forest:
    value:
        bootstrap: true
        ccp_alpha: 0
        class_weight: balanced
        criterion: gini
        max_depth: 13
        max_features: null
        max_leaf_nodes: null
        max_samples: null
        min_impurity_decrease: 0
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0
        n_estimators: 100
        n_jobs: null
        oob_score: false
        random_state: 42
        verbose: 0
        warm_start: false
tfidf:
    value:
        max_features: 10
