_wandb:
    value:
        cli_version: 0.21.3
        e:
            tx0vw3ii6konay8m4pk2eea0isintc6a:
                args:
                    - --input_artifact
                    - preprocessed_data.csv:latest
                    - --artifact_root
                    - data
                    - --artifact_type
                    - segregated_data
                    - --test_size
                    - "0.3"
                    - --random_state
                    - "42"
                    - --stratify
                    - genre
                codePath: starter/segregate/run.py
                codePathLocal: run.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "20741795840"
                email: 3ziz9788@gmail.com
                executable: /home/aziz9788/miniconda3/envs/mlflow-2b05c334639a6588d5c96ec48ecc7de59f6ca254/bin/python
                git:
                    commit: 08bac113ceb53fddf848307bff53a248e7317fe6
                    remote: https://github.com/Abdulaziz-97/pipe-line.git
                gpu: NVIDIA GeForce RTX 2080 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2080 SUPER
                      uuid: GPU-76bcb42e-862b-9f0c-a767-8fcec33ef32e
                host: DESKTOP-H5LB02V
                memory:
                    total: "8296493056"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/aziz9788/pipe-line/starter/segregate/run.py
                python: CPython 3.13.7
                root: /home/aziz9788/pipe-line/starter/segregate
                startedAt: "2025-09-24T19:30:52.645829Z"
                writerId: tx0vw3ii6konay8m4pk2eea0isintc6a
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "4": 3.13.7
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
